/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PropostasRouteImport } from './routes/propostas'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as FunilRouteImport } from './routes/funil'
import { Route as EmailsRouteImport } from './routes/emails'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'

const PropostasRoute = PropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const FunilRoute = FunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsRoute = EmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/chats': typeof ChatsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/emails': typeof EmailsRoute
  '/funil': typeof FunilRoute
  '/painel': typeof PainelRoute
  '/propostas': typeof PropostasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/chats': typeof ChatsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/emails': typeof EmailsRoute
  '/funil': typeof FunilRoute
  '/painel': typeof PainelRoute
  '/propostas': typeof PropostasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/chats': typeof ChatsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/emails': typeof EmailsRoute
  '/funil': typeof FunilRoute
  '/painel': typeof PainelRoute
  '/propostas': typeof PropostasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/chats'
    | '/configuracoes'
    | '/emails'
    | '/funil'
    | '/painel'
    | '/propostas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/chats'
    | '/configuracoes'
    | '/emails'
    | '/funil'
    | '/painel'
    | '/propostas'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/chats'
    | '/configuracoes'
    | '/emails'
    | '/funil'
    | '/painel'
    | '/propostas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ChatsRoute: typeof ChatsRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EmailsRoute: typeof EmailsRoute
  FunilRoute: typeof FunilRoute
  PainelRoute: typeof PainelRoute
  PropostasRoute: typeof PropostasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/propostas': {
      id: '/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof PropostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funil': {
      id: '/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof FunilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails': {
      id: '/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof EmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ChatsRoute: ChatsRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EmailsRoute: EmailsRoute,
  FunilRoute: FunilRoute,
  PainelRoute: PainelRoute,
  PropostasRoute: PropostasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
